config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  get 'meganes/index'
  resources :tops
  resources :meganes
  resources :connects
  resources :csv_exports, only: [] do
    collection do
      get 'export'
    end
    end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/connect.rb
class Connect < ApplicationRecord
end

app/models/csv_export.rb
class CsvExport < ApplicationRecord
end

app/models/megane.rb
class Megane < ApplicationRecord
    validates :title, presence: true
    validates :name, presence: true
    validates :content, length: {minimum:5, maximum:255}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
#----------------- devise関連の設定--------------------
    def after_sign_in_path_for(resource)
        tops_path
      end

    def after_sign_out_path_for(resource)
        user_session_path
      end
end

app/controllers/connects_controller.rb
class ConnectsController < ApplicationController
    def index
        @connects = Connect.all
    end

    def new
        @connect = Connect.new
    end

    def create
        @connect = Connect.new(connect_params)

        if @connect.save
            redirect_to meganes_path
         else 
            render 'new',status: :unprocessable_entity
         end
    end

    private
    def connect_params
        params.require(:connect).permit(:name,:name_kana,:email,:tel_number,:inquiry,:content)
    end
end

app/controllers/csv_exports_controller.rb
class CsvExportsController < ApplicationController

    def export
        # データを取得するロジックを実装
        @data = Megane.all
    
        respond_to do |format|
          format.csv do
            # CSVファイルの生成と書き込み
            csv_data = CSV.generate do |csv|
              csv << ['Title', 'Name', 'Content'] # CSVのヘッダー行
              @data.each do |record|
                csv << [record.title, record.name, record.content] # データ行
              end
            end
    
            # ファイル名を指定してCSVデータを送信
            send_data csv_data, filename: "data_export_#{Time.now.strftime('%Y%m%d_%H%M%S')}.csv"
          end
        end
      end
end

app/controllers/meganes_controller.rb
class MeganesController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @meganes = Megane.all
  end

  def new
    @megane = Megane.new
  end

  def create
    @megane = Megane.new(megane_params)

    if @megane.save
       redirect_to meganes_path
    else 
       render 'new',status: :unprocessable_entity
    end
  
  end
  
  def show
    @megane = Megane.find(params[:id]);
  end

  def destroy
    @megane = Megane.find(params[:id]);
    if @megane.destroy
      flash[:notice] = '記録が削除されました。'
      redirect_to meganes_path
    end
  end

  private
  def megane_params
    params.require(:megane).permit(:title ,:name ,:content)
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/connects_helper.rb
module ConnectsHelper
end

app/helpers/csv_exports_helper.rb
module CsvExportsHelper
end

app/helpers/meganes_helper.rb
module MeganesHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/connects/index.html.erb
<%= render 'shared/header' %>
<h1>問い合わせ内容</h1>
<table border="1">
  <tr>
    <th>お名前</th>
    <th>ふりがな</th>
    <th>アドレス</th>
    <th>電話番号</th>
    <th>種類</th>
    <th>問い合わせ内容</th>
    <th>日時</th>
    
  </tr>
<% @connects.each do |connect|%>
<tr>
    <td><%=connect.name%></td>
    <td><%=connect.name_kana%></td>
    <td><%=connect.email%></td>
    <td><%=connect.tel_number%></td>
    <td><%=connect.inquiry%></td>
    <td><%=connect.content%></td>
    <td><%=connect.created_at.strftime('%Y-%m-%d %H:%M:%S')%></td>
</tr>
<%end%>

app/views/connects/new.html.erb
<%= render 'shared/header' %>
<h1>登録ページ</h1>

<%= form_with model:@connect do |form| %>
    <% if @connect.errors.any?%>
    <div style="color: red;">
        <ul>
        <% @connect.errors.full_messages.each do |message|%>
        <li><%= message %></li>
        <%end%>
        </ul>
    </div>
    <%end%>

<div class="form_top">
    <%= form.label :name%>
    <%= form.text_field :name%>
    
    
    <%= form.label :name_kana%>
    <%= form.text_field :name_kana%>

    <%= form.label :email%>
    <%= form.text_field :email%>

    <%= form.label :tel_number%>
    <%= form.text_field :tel_number%>

    <%= form.label :inquiry%>
    <div class="radio-buttons">
    <%= form.radio_button :inquiry,"1"%>メガネ
    <%= form.radio_button :inquiry,"2"%>コンタクト
    <%= form.radio_button :inquiry,"3"%>その他
    </div>

    <%= form.label :content%>
    <%= form.text_area :content%>

    <%=form.submit %>
    </div>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MeganeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

<!-- <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %> -->
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/meganes/index.html.erb
<%= render 'shared/header' %>

<!--
<% flash.each do |key, value| %>
  <div class="flash <%= key %>">
    <%= value %>
  </div>
<% end %>
-->
<div class='main'>
<h1>Meganes</h1>
<div >
<%= link_to 'create', new_megane_path, class:"create-btn"%>
</div>
<table border="1">
  <tr>
    <th>title</th>
    <th>name</th>
    <th>content</th>
  </tr>
  <% @meganes.each do |megane| %>
    <tr>
      <td><%= megane.title %></td>
      <td><%= megane.name %></td>
      <td><%= megane.content %></td>
      <td><%= link_to '詳細', megane_path(megane) %></td>
      <td><%= link_to '削除', megane_path(megane), data: { turbo_method: 'delete', turbo_confirm: '本当に削除しますか？' } %></td>
    </tr>
  <% end %>
</table>
</div>

<div>
<%= link_to 'CSVエクスポート', export_csv_exports_path(format: :csv), class: 'btn btn-primary' %>
</div>
<%= link_to 'お問い合わせ',new_connect_path %>

app/views/meganes/new.html.erb
<%= render 'shared/header' %>

<h1>登録ページ</h1>
<%= form_with model:@megane do |form| %>
    <% if @megane.errors.any?%>
    <div style="color: red;">
        <ul>
        <% @megane.errors.full_messages.each do |message|%>
        <li><%= message %></li>
        <%end%>
        </ul>
    </div>
    <%end%>

    <div>
    <%= form.label :title%>
    <%= form.text_field :title%>
    </div>
    <div>
    <%= form.label :name%>
    <%= form.text_field :name%>
    </div>
    <div>
    <%= form.label :content%>
    <%= form.text_area :content%>
    </div>
    <%=form.submit %>
<%end%>

app/views/meganes/show.html.erb
<%= render 'shared/header' %>

<h1> Show </h1>
<table border="1">
  <tr>
    <th>title</th>
    <th>name</th>
    <th>content</th>
  </tr>
  <tr>
    <td><%= @megane.title %></td>
    <td><%= @megane.name %></td>
    <td><%= @megane.content %></td>
 </tr>


 </table>
 <%=link_to "back" ,meganes_path %>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
<div class='nav'>
    <ul class='logo-left'>
      <li><%= link_to image_tag("megane.png", class:"logo"), "/meganes", class: "logo" %></li>
    </ul>

    <ul class='lists-right'>
    <% if user_signed_in? %> <!-- ユーザーがログインしていた時の処理 -->
       <%# <h4> メールアドレス： <%= current_user.email ,class: "user-nickname" </h4>  %>
      <li><%= link_to "ログアウト", destroy_user_session_path, method: :get ,class: "logout"%> </li><!-- ログアウトをする -->
    <% else %> <!-- ユーザーがログインしていなかった時の処理 -->
      <li><%= link_to "ログイン", new_user_session_path, class: 'post',class: "login" %></li> <!-- ログイン画面に移行する -->
      <li><%= link_to "新規登録", new_user_registration_path, class: 'post' ,class: "sign-up"%></li> <!-- 新規登録画面に移行する -->
    <% end %>

    </ul>
  </div>
</header>

app/views/tops/index.html.erb
<%= render 'shared/header' %>

<div class="top-mainpage">
    <div class="top-link">
        <%=link_to "案件対応一覧" ,meganes_path ,class:"link-btn"%>
        <%=link_to "問い合わせ確認" ,connects_path,class:"link-btn"%>
        <%=link_to "問い合わせ" ,new_connect_path,class:"link-btn"%>
    </div>
</div>